# fly.toml app configuration file generated for creator-fluent-worker on 2026-01-22T05:35:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'creator-fluent-worker'
primary_region = 'iad'

[build]

[processes]
  app = "node dist/runAll.js"

[deploy]
  strategy = "rolling"

[[vm]]
  memory_mb = 1024
  cpu_kind = 'shared'
  cpus = 1
